services:
  clip-init:
    image: clip-retrieval:latest
    container_name: clip-init
    profiles: ["init"]
    env_file: .env
    entrypoint: |
      /bin/bash -c "
        sleep 5

        source .venv/bin/activate

        cd /app/test_and_scripts/test
        
        if [ ! -f ${OUTPUT_FOLDER}/.init_done ]; then
          clip-retrieval end2end test_10000.parquet ${OUTPUT_FOLDER}
          touch ${OUTPUT_FOLDER}/.init_done
        else
          echo 'Init already done, skipping'
        fi
      "
    restart: "no"
    shm_size: 2g
    volumes:
      - clip-data:/app/test_and_scripts/test/${OUTPUT_FOLDER}
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]


  clip-back:
    image: clip-retrieval:latest
    container_name: clip-back
    env_file: .env
    ports:
      - "${HOST_PORT}:${BACKEND_PORT}"
    entrypoint: |
      /bin/bash -c '
      sleep 5

      source .venv/bin/activate

      cd /app/test_and_scripts/test

      clip-retrieval back --port ${BACKEND_PORT} --indices_paths ${OUTPUT_FOLDER}/indices_paths.json
      '
    restart: on-failure
    shm_size: 2g
    volumes:
      - clip-data:/app/test_and_scripts/test/${OUTPUT_FOLDER}
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${BACKEND_PORT}/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20
      start_period: 120s

  requests-client:
    image: clip-retrieval:latest
    container_name: requests-client
    env_file: .env
    volumes:
      - clip-scripts:/app/test_and_scripts/scripts
    command: >
      bash -c "
        sleep 5;
        source .venv/bin/activate;
        python /app/test_and_scripts/scripts/run_requests_from_excel.py
      "
    depends_on:
      clip-back:
        condition: service_healthy
    restart: on-failure

volumes:
  clip-data:
  clip-scripts: