services:
  clip-init:
    image: kacbuj17/clip-retrieval:${CLIP_RETRIEVAL_VERSION}
    container_name: clip-init
    profiles: ["init"]
    env_file: .env
    entrypoint: |
      /bin/bash -c "
        sleep 5
        source .venv/bin/activate
        cd /app/test_and_scripts/scripts
        
        if [ ! -f ${RESOURCES_FOLDER}/.init_done ]; then
          python end2end_customData.py
          touch ${RESOURCES_FOLDER}/.init_done
        else
          echo 'Init already done, skipping'
        fi
      "
    restart: on-failure
    shm_size: 2g
    volumes:
      - ./clip-data:/app/test_and_scripts/scripts/${RESOURCES_FOLDER}
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]


  clip-back:
    image: kacbuj17/clip-retrieval:${CLIP_RETRIEVAL_VERSION}
    container_name: clip-back
    env_file: .env
    ports:
      - "${HOST_PORT}:${BACKEND_PORT}"
    entrypoint: |
      /bin/bash -c '
      sleep 5
      source .venv/bin/activate
      cd /app/test_and_scripts/scripts
      python run_back.py
      '
    restart: on-failure
    shm_size: 2g
    volumes:
      - ./clip-data:/app/test_and_scripts/scripts/${RESOURCES_FOLDER}
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: all
            capabilities: [gpu]
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:${BACKEND_PORT}/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 300s

  requests-client:
    image: kacbuj17/clip-retrieval:${CLIP_RETRIEVAL_VERSION}
    container_name: requests-client
    env_file: .env
    volumes:
      - ./clip-data:/app/test_and_scripts/scripts/${RESOURCES_FOLDER}
    command: >
      bash -c "
        sleep 5;
        source .venv/bin/activate;
        cd /app/test_and_scripts/scripts;
        python run_requests_from_excel.py
      "
    depends_on:
      clip-back:
        condition: service_healthy
    restart: on-failure